### ISSUE TITLE
Could you please tell me that how to run this project and configure args of project? Thanks

### ISSUE THREAD

**Issue by whxloveyrh** [punit-naik/MLHadoop#1]
![2015-11-28 22 34 37](https://cloud.githubusercontent.com/assets/10508811/11452366/3bbb28de-9620-11e5-9b5f-e1affd5da710.png)
project:MatrixMultiplication_MapReduce
class:MatMulDriver.java
Could you please tell me that how to run the project and configure args of the project? Thanks
Could you please tell me that how to run the project and configure args of the project? Thanks
I don't know this means,as follow:
        conf.set("m", args[0]);
    conf.set("n", args[1]);
    conf.set("p", args[2]);

**Comment by whxloveyrh** [comment]
my email:wang010366@vip.qq.com
Could you please tell me that how to solve this problem?
![2015-11-28 22 40 49](https://cloud.githubusercontent.com/assets/10508811/11452384/1de77438-9621-11e5-9c8a-94e9187260e8.png)

**Comment by whxloveyrh** [comment]
![2015-11-29 20 53 08](https://cloud.githubusercontent.com/assets/10508811/11457109/43459f24-96db-11e5-9258-1c13a789b38f.png)
I don't know how to configure the program arguments,Could you write a example  for me? Thanks
project:Recommendation_Collaborative_Filtering_MapReduce
thank you very much

**Comment by punit-naik** [comment]
1. m  x n are the dimensions of the first matrix and n x p are the dimensions of the second matrix. So in the program arguments box, you should give these three integer values separated by a new line. Frankly speaking, you should not be asking these type of silly questions.
2. I think I have explained myself very clearly in the readme files of every algorithm. These programs are for pirely educational purposes and your request for asking me to write an example code for you is completely ridiculous. Go and figure it out for yourself.

I mean no offence.
